
# Netlify configuration file

[build]
  # Build command for Vite React project
  command = "npm run build"
  # Output directory for Vite builds
  publish = "dist"

# This redirect rule tells Netlify to serve the index.html for any route
# This is necessary for single-page applications with client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add headers for improved security and performance
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' https://cdn.gpteng.co 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self'; connect-src 'self' https:;"
